#   Question 1

#   Naive Bayes for Salary Dataset

In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

###    Analyzing the Train dataset

In [97]:
salary_train = pd.read_csv("SalaryData_Train.csv")
salary_train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [98]:
salary_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [99]:
salary_train1 = salary_train[salary_train.duplicated()]
salary_train1.head()

age workclass   education  educationno        maritalstatus  \
326   33   Private   Bachelors           13   Married-civ-spouse   
364   27   Private   Bachelors           13        Never-married   
518   24   Private     HS-grad            9        Never-married   
525   24   Private     HS-grad            9        Never-married   
619   33   Private   Bachelors           13   Married-civ-spouse   

             occupation    relationship    race      sex  capitalgain  \
326     Exec-managerial         Husband   White     Male            0   
364        Craft-repair   Not-in-family   White     Male            0   
518   Handlers-cleaners       Unmarried   Black   Female            0   
525        Craft-repair       Own-child   White     Male            0   
619     Exec-managerial         Husband   White     Male            0   

     capitalloss  hoursperweek          native  Salary  
326            0            40   United-States    >50K  
364            0            50   United-States   <=50K  
518            0            40   United-States   <=50K  
525            0            40   United-States   <=50K  
619            0            40   United-States    >50K

In [100]:
salary_train2 = salary_train.drop_duplicates().reset_index(drop=True)
salary_train2.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [101]:
salary_train2.workclass = salary_train2.workclass.astype('category').cat.codes
salary_train2.education = salary_train2.education.astype('category').cat.codes
salary_train2.maritalstatus = salary_train2.maritalstatus.astype('category').cat.codes
salary_train2.occupation = salary_train2.occupation.astype('category').cat.codes
salary_train2.relationship = salary_train2.relationship.astype('category').cat.codes
salary_train2.race = salary_train2.race.astype('category').cat.codes
salary_train2.sex = salary_train2.sex.astype('category').cat.codes
salary_train2.native = salary_train2.native.astype('category').cat.codes
salary_train2.Salary = salary_train2.Salary.astype('category').cat.codes

In [102]:
salary_train2.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          9           13              4           0   
1   50          4          9           13              2           3   
2   38          2         11            9              0           5   
3   53          2          1            7              2           5   
4   28          2          9           13              2           9   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1         2174            0            40      37   
1             0     4    1            0            0            13      37   
2             1     4    1            0            0            40      37   
3             0     2    1            0            0            40      37   
4             5     2    0            0            0            40       4   

   Salary  
0       0  
1       0  
2       0  
3       0  
4       0

In [103]:
salary_train3 = salary_train2.values

In [104]:
salary_train3

array([[39,  5,  9, ..., 40, 37,  0],
       [50,  4,  9, ..., 13, 37,  0],
       [38,  2, 11, ..., 40, 37,  0],
       ...,
       [27,  2,  7, ..., 38, 37,  0],
       [58,  2, 11, ..., 40, 37,  0],
       [52,  3, 11, ..., 40, 37,  1]], dtype=int64)

In [105]:
x_sal_train = salary_train3[:,0:13]
x_sal_train

array([[39,  5,  9, ...,  0, 40, 37],
       [50,  4,  9, ...,  0, 13, 37],
       [38,  2, 11, ...,  0, 40, 37],
       ...,
       [27,  2,  7, ...,  0, 38, 37],
       [58,  2, 11, ...,  0, 40, 37],
       [52,  3, 11, ...,  0, 40, 37]], dtype=int64)

In [106]:
y_sal_train = salary_train3[:,13]
y_sal_train

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

###     Standardizing the train dataset

In [107]:
train_sal = StandardScaler().fit_transform(x_sal_train)
train_sal

array([[-0.00372591,  2.79138305, -0.32451893, ..., -0.23132996,
        -0.09432316,  0.28241436],
       [ 0.83032903,  1.78815577, -0.32451893, ..., -0.23132996,
        -2.28112073,  0.28241436],
       [-0.07954909, -0.2182988 ,  0.19299932, ..., -0.23132996,
        -0.09432316,  0.28241436],
       ...,
       [-0.91360403, -0.2182988 , -0.84203718, ..., -0.23132996,
        -0.25630817,  0.28241436],
       [ 1.43691444, -0.2182988 ,  0.19299932, ..., -0.23132996,
        -0.09432316,  0.28241436],
       [ 0.98197538,  0.78492849,  0.19299932, ..., -0.23132996,
        -0.09432316,  0.28241436]])

###    Analyzing the Test dataset

In [108]:
salary_test = pd.read_csv("SalaryData_Test.csv")
salary_test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [109]:
salary_test1 = salary_test[salary_test.duplicated()]
salary_test1.head()

age workclass     education  educationno        maritalstatus  \
551    59   Private       HS-grad            9             Divorced   
601    32   Private       HS-grad            9   Married-civ-spouse   
681    40   Private       HS-grad            9   Married-civ-spouse   
799    24   Private     Bachelors           13        Never-married   
1044   44   Private   Prof-school           15   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
551     Other-service   Not-in-family   White   Female            0   
601             Sales         Husband   White     Male            0   
681      Craft-repair         Husband   White     Male            0   
799    Prof-specialty   Not-in-family   White     Male            0   
1044   Prof-specialty         Husband   White     Male        99999   

      capitalloss  hoursperweek          native  Salary  
551             0            40   United-States   <=50K  
601             0            40   United-States   <=50K  
681             0            40   United-States   <=50K  
799             0            35   United-States   <=50K  
1044            0            60   United-States    >50K

In [110]:
salary_test2 = salary_test.drop_duplicates().reset_index(drop=True)
salary_test2.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [111]:
salary_test2.workclass = salary_test2.workclass.astype('category').cat.codes
salary_test2.education = salary_test2.education.astype('category').cat.codes
salary_test2.maritalstatus = salary_test2.maritalstatus.astype('category').cat.codes
salary_test2.occupation = salary_test2.occupation.astype('category').cat.codes
salary_test2.relationship = salary_test2.relationship.astype('category').cat.codes
salary_test2.race = salary_test2.race.astype('category').cat.codes
salary_test2.sex = salary_test2.sex.astype('category').cat.codes
salary_test2.native = salary_test2.native.astype('category').cat.codes
salary_test2.Salary = salary_test2.Salary.astype('category').cat.codes

In [112]:
salary_test2.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            7              4           6   
1   38          2         11            9              2           4   
2   28          1          7           12              2          10   
3   44          2         15           10              2           6   
4   34          2          0            6              4           7   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            40      37   
1             0     4    1            0            0            50      37   
2             0     4    1            0            0            40      37   
3             0     2    1         7688            0            40      37   
4             1     4    1            0            0            30      37   

   Salary  
0       0  
1       0  
2       1  
3       1  
4       0

In [113]:
salary_test3 = salary_test2.values
salary_test3

array([[25,  2,  1, ..., 40, 37,  0],
       [38,  2, 11, ..., 50, 37,  0],
       [28,  1,  7, ..., 40, 37,  1],
       ...,
       [38,  2,  9, ..., 50, 37,  0],
       [44,  2,  9, ..., 40, 37,  0],
       [35,  3,  9, ..., 60, 37,  1]], dtype=int64)

In [114]:
x_sal_test = salary_test3[:,0:13]
x_sal_test

array([[25,  2,  1, ...,  0, 40, 37],
       [38,  2, 11, ...,  0, 50, 37],
       [28,  1,  7, ...,  0, 40, 37],
       ...,
       [38,  2,  9, ...,  0, 50, 37],
       [44,  2,  9, ...,  0, 40, 37],
       [35,  3,  9, ...,  0, 60, 37]], dtype=int64)

In [115]:
y_sal_test = salary_test3[:,13]
y_sal_test

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

###    Standardizing the test dataset 

In [116]:
test_sal = StandardScaler().fit_transform(x_sal_test)
test_sal

array([[-1.05408752, -0.22877429, -2.38547513, ..., -0.22610763,
        -0.08753833,  0.26950358],
       [-0.08603828, -0.22877429,  0.20086709, ..., -0.22610763,
         0.72761694,  0.26950358],
       [-0.83069154, -1.23706521, -0.8336698 , ..., -0.22610763,
        -0.08753833,  0.26950358],
       ...,
       [-0.08603828, -0.22877429, -0.31640136, ..., -0.22610763,
         0.72761694,  0.26950358],
       [ 0.36075367, -0.22877429, -0.31640136, ..., -0.22610763,
        -0.08753833,  0.26950358],
       [-0.30943426,  0.77951663, -0.31640136, ..., -0.22610763,
         1.54277221,  0.26950358]])

###    Gaussian Naive Bayes

In [117]:
classifier_gnb = GaussianNB()
classifier_gnb.fit(train_sal, y_sal_train)

GaussianNB()

In [118]:
y_pred = classifier_gnb.predict(test_sal)
y_pred

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [119]:
accuracy_gnb = accuracy_score(y_sal_test,y_pred)
accuracy_gnb

0.7977353149327672

In [120]:
confusion_gnb = confusion_matrix(y_sal_test, y_pred)
confusion_gnb

array([[10057,   563],
       [ 2295,  1215]], dtype=int64)

In [121]:
print(classification_report(y_sal_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.95      0.88     10620
           1       0.68      0.35      0.46      3510

    accuracy                           0.80     14130
   macro avg       0.75      0.65      0.67     14130
weighted avg       0.78      0.80      0.77     14130

